const menu = {
    list() {
        return [
					{
						"backMenu":[
							{
								"child":[
									{
										"buttons":[
											"新增",
											"查看",
											"修改",
											"删除"
										],
										"menu":"用户",
										"menuJump":"列表",
										"tableName":"yonghu"
									}
								],
								"menu":"用户管理"
							},
							{
								"child":[
									{
										"buttons":[
											"新增",
											"查看",
											"修改",
											"删除"
										],
										"menu":"食物库存",
										"menuJump":"列表",
										"tableName":"kuchuen"
									}
								],
								"menu":"食物库存管理"
							},
							{
								"child":[
									{
										"buttons":[
											"新增",
											"查看",
											"修改",
											"删除",
										],
										"menu":"海鲜展示",
										"menuJump":"列表",
										"tableName":"haixian"
									}
								],
								"menu":"海鲜展示管理"
							},
							{
								"child":[
									{
										"buttons":[
											"新增",
											"查看",
											"修改",
											"删除",
										],
										"menu":"未预定餐桌",
										"menuJump":"列表",
										"tableName":"canzhuo"
									}
								],
								"menu":"未预定餐桌管理"
							},
							{
								"child":[
									{
										"buttons":[
											"查看",
											"删除"
										],
										"menu":"已预定餐桌",
										"menuJump":"列表",
										"tableName":"yudingcanzhuo"
									}
								],
								"menu":"已预定餐桌管理"
							},
							{
								"child":[
									{
										"buttons":[
											"查看",
											"删除",
                                            "修改",
										],
										"menu":"流水",
										"menuJump":"列表",
										"tableName":"liushui"
									}
								],
								"menu":"流水管理"
							},

						],
						"frontMenu":[],
						"hasBackLogin":"是",
						"hasBackRegister":"否",
						"hasFrontLogin":"否",
						"hasFrontRegister":"否",
						"roleName":"管理员",
						"tableName":"users"
					},
					{
						"backMenu":[
							{
								"child":[
									{
										"buttons":[
											"查看",
											"点餐"
										],
										"menu":"海鲜展示",
										"menuJump":"列表",
										"tableName":"haixian"
									}
								],
								"menu":"海鲜展示管理"
							},
							{
								"child":[
									{
										"buttons":[
											"查看",
											'预定'
										],
										"menu":"未预定餐桌",
										"menuJump":"列表",
										"tableName":"canzhuo"
									}
								],
								"menu":"未预定餐桌管理"
							},
							{
								"child":[
									{
										"buttons":[
											"查看",
											"删除"
										],
										"menu":"已预定餐桌",
										"menuJump":"列表",
										"tableName":"yudingcanzhuo"
									}
								],
								"menu":"已预定餐桌管理"
							},
							{
								"child":[
									{
										"buttons":[
											"查看",
										],
										"menu":"订单纪录",
										"menuJump":"列表",
										"tableName":"liushui"
									}
								],
								"menu":"订单管理"
							},
						],
						"frontMenu":[],
						"hasBackLogin":"是",
						"hasBackRegister":"否",
						"hasFrontLogin":"否",
						"hasFrontRegister":"否",
						"roleName":"用户",
						"tableName":"yonghu"
					}
				]
		}
}
export default menu;
